@host = http://localhost:3000
@createHostId = {{createHost.response.body.id}}
@token = {{signin.response.body.token}}

//¬~{&}13oct¬~{&}
### get /
GET {{host}}/


### get /hello/en?name=
# Query parameters
GET {{host}}/hello/en?name=Thiago


### get /hello/en/:name'
# Route parameters
GET {{host}}/hello/en/Thiago


### post /hello/es
# Body parameters
POST {{host}}/hello/en
Content-Type: application/json

{
  "name": "Thiago"
}



# =====19.oct=====
### Get latency

GET {{host}}/hosts/1/times

### Get latency with specific count

GET {{host}}/hosts/1/times?count=5



//¬~{&}30octprojct¬~{&}
### Get 
GET {{host}}/api/1/status



//¬~{&}9nov¬~{&}
### List all Hosts
GET {{host}}/hosts
Authorization: bearer {{token}}

### Create Host
# @name createHost
POST {{host}}/hosts
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Cloudflare",
  "address": "1.1.1.0"
}

### Update Host

PUT {{host}}/hosts/{{createHostId}}
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Cloudflare",
  "address": "1.1.1.1"
}

### Remove Host

DELETE {{host}}/hosts/{{createHostId}}



### List Users

GET {{host}}/users
Authorization: bearer {{token}}

### Create User

# @name createUser
POST {{host}}/users
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Thiago",
  "email": "thiago@gmail.com",
  "password": "123"
}


### Update User

PUT {{host}}/users/{{createHostId}}
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Abrantes",
  "email": "Abrantes@gmail.com"
}


### Delete User

DELETE {{host}}/users/{{createHostId}}
Authorization: bearer {{token}}


### Signin
### only when create USER exists

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "thiago@gmail.com",
  "password": "123"
}


### Signin 401 not found

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "thiago@email.com",
  "password": "321"
}





### Get latency
### only when create hosts exists
GET {{host}}/hosts/{{createHostId}}/times
Authorization: bearer {{token}}

### Get latency with specific count

GET {{host}}/hosts/{{createHostId}}/times?count=3
Authorization: bearer {{token}}






//¬~{&}12octprojct¬~{&}
### Get All API
GET {{host}}/status


### Create API
# @name createHost
POST {{host}}/status
Content-Type: application/json

{
  "name": "Uol",
  "protocolo": "http",
  "address": "asgoogle.com.br"
}

### Remove API

DELETE {{host}}/status/c5cc453d-4538-451f-a7dd-33ce9bd1d11b


### Update API

PUT {{host}}/status/{{createHostId}}
Content-Type: application/json

{
  "name": "ifpb",
  "address": "dados.ifpb.edu.brrrrrrrr"
}



### Get 
### only when create API exists
GET {{host}}/status/{{createHostId}}/

### Get status api
### only when create API exists
GET {{host}}/status/api
