@host = http://localhost:3000
@token = {{signin.response.body.token}}


### List Users

GET {{host}}/users/
Authorization: bearer {{token}}

### Create User

# @name createUser
POST {{host}}/users
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Thiago",
  "email": "thiago@gmail.com",
  "password": "123",
  "fusoh": "America/Sao_Paulo",
  "horarioverao": "sim",
  "infoeyesup": "sim",
  "infoparc": "sim"

}

### Update User

PUT {{host}}/users/10
Content-Type: application/json
Authorization: bearer {{token}}

{
  "name": "Abrantes",
  "email": "Abrantes@gmail.com"
}


### Delete User

DELETE {{host}}/users/15
Authorization: bearer {{token}}


### Signin
### only when create USER exists

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "thiago@gmail.com",
  "password": "123"
}


### Signin 401 not found

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "thiago@email.com",
  "password": "321"
}










//¬~{&}12octprojct¬~{&}
### Get All API
GET {{host}}/status


### Create API
#inform the id of the user
# @name createStatusController
POST {{host}}/status/32
Content-Type: application/json

{
  "name": "globzzz",
  "protocolo": "http",
  "address": "zzzzzlolgggloballl.com.br"
}

### Remove API

DELETE {{host}}/status/47


### Update API

PUT {{host}}/status/17
Content-Type: application/json

{
  "name": "ifpb",
  "address": "dados.ifpb.edu.brrrrrrrr"
}



### Get 
### only when create API exists
GET {{host}}/status/78

### Get status api
### only when create API exists
GET {{host}}/status/api


### Get send notification
POST {{host}}/send
Content-Type: application/json

{
  "email": "caway28271@dmonies.com",
  "subject": "EyesUp - Notificação!",
  "message": "<h1>Olá Usuário!</h1> <p>você está recebendo essa notificação porque seu site está fora do ar. Acesse o EyesUp para mais informações.</p>"
}


### Get ip return
#inform the id of the status host
GET {{host}}/ip/80

