### List API-IFPB

GET http://localhost:3000/API-IFPB

### Get first host

GET http://localhost:3000/API-IFPB/12

### Create host

POST http://localhost:3000/API-IFPB
Content-Type: application/json

{
  "name": "Cloudflare",
  "address": "1.1.1.1"
}

### Update host

PUT http://localhost:3000/API-IFPB/3
Content-Type: application/json

{
  "name": "Cloudflare DNS",
  "address": "1.1.1.1"
}

### Delete host

DELETE http://localhost:3000/API-IFPB/4